name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        run: |
          git clone --branch main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .

      - name: Install Node.js & Build directly
        run: |
          # Utilise directement la version de Node disponible sur l'environnement Linux sans action intermédiaire
          node -v
          npm install
          npm run build
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
